[2023-10-06 11:07:45,083] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_fligoo_etl_v2.run_etl_task manual__2023-10-06T11:07:42.671901+00:00 [queued]>
[2023-10-06 11:07:45,110] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_fligoo_etl_v2.run_etl_task manual__2023-10-06T11:07:42.671901+00:00 [queued]>
[2023-10-06 11:07:45,111] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-10-06 11:07:45,111] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2023-10-06 11:07:45,111] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-10-06 11:07:45,139] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): run_etl_task> on 2023-10-06 11:07:42.671901+00:00
[2023-10-06 11:07:45,146] {standard_task_runner.py:52} INFO - Started process 2828 to run task
[2023-10-06 11:07:45,153] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_fligoo_etl_v2', 'run_etl_task', 'manual__2023-10-06T11:07:42.671901+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_fligoo_etl.py', '--cfg-path', '/tmp/tmpiaa9arj0', '--error-file', '/tmp/tmp5ohvy85f']
[2023-10-06 11:07:45,154] {standard_task_runner.py:77} INFO - Job 6: Subtask run_etl_task
[2023-10-06 11:07:45,236] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_fligoo_etl_v2.run_etl_task manual__2023-10-06T11:07:42.671901+00:00 [running]> on host f0647ca95f12
[2023-10-06 11:07:45,322] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=dag_fligoo_etl_v2
AIRFLOW_CTX_TASK_ID=run_etl_task
AIRFLOW_CTX_EXECUTION_DATE=2023-10-06T11:07:42.671901+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-06T11:07:42.671901+00:00
[2023-10-06 11:07:45,323] {logging_mixin.py:109} INFO - >>> Running 'etl' function. Logged at 2023-10-06 11:07:45.323751+00:00
[2023-10-06 11:07:45,324] {logging_mixin.py:109} INFO - >>> Running 'connect_db' function. Logged at 2023-10-06 11:07:45.324323+00:00
[2023-10-06 11:07:45,324] {logging_mixin.py:109} INFO - Connecting to DB
[2023-10-06 11:07:45,337] {logging_mixin.py:109} INFO - >>> Function: 'connect_db' executed. Logged at 2023-10-06 11:07:45.324323+00:00
[2023-10-06 11:07:45,337] {logging_mixin.py:109} INFO - >>> Running 'extract' function. Logged at 2023-10-06 11:07:45.337697+00:00
[2023-10-06 11:07:45,338] {logging_mixin.py:109} INFO - Reading dataset from http://api.aviationstack.com/v1/flights
[2023-10-06 11:07:46,194] {logging_mixin.py:109} INFO - >>> Function: 'extract' executed. Logged at 2023-10-06 11:07:45.337697+00:00
[2023-10-06 11:07:46,195] {logging_mixin.py:109} INFO - >>> Running 'transform' function. Logged at 2023-10-06 11:07:46.195115+00:00
[2023-10-06 11:07:46,195] {logging_mixin.py:109} INFO - Transforming data
[2023-10-06 11:07:46,220] {warnings.py:110} WARNING - /opt/***/dags/dag_fligoo_etl.py:107: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['departure_timezone'] = df['departure_timezone'].str.replace('/', ' - ')

[2023-10-06 11:07:46,222] {warnings.py:110} WARNING - /opt/***/dags/dag_fligoo_etl.py:108: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['arrival_timezone'] = df['arrival_timezone'].str.replace('/', ' - ')

[2023-10-06 11:07:46,223] {logging_mixin.py:109} INFO - >>> Function: 'transform' executed. Logged at 2023-10-06 11:07:46.195115+00:00
[2023-10-06 11:07:46,223] {logging_mixin.py:109} INFO - >>> Running 'load_to_db' function. Logged at 2023-10-06 11:07:46.223831+00:00
[2023-10-06 11:07:46,224] {logging_mixin.py:109} INFO - Loading dataframe to DB on table: testdata
[2023-10-06 11:07:46,309] {logging_mixin.py:109} INFO - >>> Function: 'load_to_db' executed. Logged at 2023-10-06 11:07:46.223831+00:00
[2023-10-06 11:07:46,311] {logging_mixin.py:109} INFO - >>> Function: 'etl' executed. Logged at 2023-10-06 11:07:45.323751+00:00
[2023-10-06 11:07:46,311] {python.py:175} INFO - Done. Returned value was: None
[2023-10-06 11:07:46,334] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag_fligoo_etl_v2, task_id=run_etl_task, execution_date=20231006T110742, start_date=20231006T110745, end_date=20231006T110746
[2023-10-06 11:07:46,376] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-10-06 11:07:46,433] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
