[2023-10-06 11:01:11,033] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_fligoo_etl.run_tables_exists_task manual__2023-10-06T11:01:06.429640+00:00 [queued]>
[2023-10-06 11:01:11,063] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_fligoo_etl.run_tables_exists_task manual__2023-10-06T11:01:06.429640+00:00 [queued]>
[2023-10-06 11:01:11,063] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-10-06 11:01:11,064] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2023-10-06 11:01:11,064] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-10-06 11:01:11,090] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): run_tables_exists_task> on 2023-10-06 11:01:06.429640+00:00
[2023-10-06 11:01:11,097] {standard_task_runner.py:52} INFO - Started process 2498 to run task
[2023-10-06 11:01:11,102] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_fligoo_etl', 'run_tables_exists_task', 'manual__2023-10-06T11:01:06.429640+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_fligoo_etl.py', '--cfg-path', '/tmp/tmp72nqsvn9', '--error-file', '/tmp/tmpbt39j4th']
[2023-10-06 11:01:11,104] {standard_task_runner.py:77} INFO - Job 4: Subtask run_tables_exists_task
[2023-10-06 11:01:11,184] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_fligoo_etl.run_tables_exists_task manual__2023-10-06T11:01:06.429640+00:00 [running]> on host f0647ca95f12
[2023-10-06 11:01:11,268] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Damian
AIRFLOW_CTX_DAG_ID=dag_fligoo_etl
AIRFLOW_CTX_TASK_ID=run_tables_exists_task
AIRFLOW_CTX_EXECUTION_DATE=2023-10-06T11:01:06.429640+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-06T11:01:06.429640+00:00
[2023-10-06 11:01:11,270] {logging_mixin.py:109} INFO - >>> Running 'tables_exists' function. Logged at 2023-10-06 11:01:11.270214+00:00
[2023-10-06 11:01:11,270] {logging_mixin.py:109} INFO - >>> Running 'connect_db' function. Logged at 2023-10-06 11:01:11.270790+00:00
[2023-10-06 11:01:11,271] {logging_mixin.py:109} INFO - Connecting to DB
[2023-10-06 11:01:11,283] {logging_mixin.py:109} INFO - >>> Function: 'connect_db' executed. Logged at 2023-10-06 11:01:11.270790+00:00
[2023-10-06 11:01:11,283] {logging_mixin.py:109} INFO - Checking if tables exists
[2023-10-06 11:01:11,283] {logging_mixin.py:109} INFO - >>> Running 'check_table_exists' function. Logged at 2023-10-06 11:01:11.283803+00:00
[2023-10-06 11:01:11,287] {logging_mixin.py:109} INFO - 'testdata' exists in the DB!
[2023-10-06 11:01:11,287] {logging_mixin.py:109} INFO - >>> Function: 'check_table_exists' executed. Logged at 2023-10-06 11:01:11.283803+00:00
[2023-10-06 11:01:11,288] {logging_mixin.py:109} INFO - >>> Function: 'tables_exists' executed. Logged at 2023-10-06 11:01:11.270214+00:00
[2023-10-06 11:01:11,289] {python.py:175} INFO - Done. Returned value was: None
[2023-10-06 11:01:11,311] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag_fligoo_etl, task_id=run_tables_exists_task, execution_date=20231006T110106, start_date=20231006T110111, end_date=20231006T110111
[2023-10-06 11:01:11,361] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-10-06 11:01:11,414] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
