[2023-10-06 11:01:08,142] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_fligoo_etl.run_etl_task manual__2023-10-06T11:01:06.429640+00:00 [queued]>
[2023-10-06 11:01:08,171] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_fligoo_etl.run_etl_task manual__2023-10-06T11:01:06.429640+00:00 [queued]>
[2023-10-06 11:01:08,172] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-10-06 11:01:08,172] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2023-10-06 11:01:08,173] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-10-06 11:01:08,203] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): run_etl_task> on 2023-10-06 11:01:06.429640+00:00
[2023-10-06 11:01:08,209] {standard_task_runner.py:52} INFO - Started process 2493 to run task
[2023-10-06 11:01:08,215] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_fligoo_etl', 'run_etl_task', 'manual__2023-10-06T11:01:06.429640+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_fligoo_etl.py', '--cfg-path', '/tmp/tmp1ndjhopv', '--error-file', '/tmp/tmpgg1o1702']
[2023-10-06 11:01:08,217] {standard_task_runner.py:77} INFO - Job 3: Subtask run_etl_task
[2023-10-06 11:01:08,298] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_fligoo_etl.run_etl_task manual__2023-10-06T11:01:06.429640+00:00 [running]> on host f0647ca95f12
[2023-10-06 11:01:08,382] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Damian
AIRFLOW_CTX_DAG_ID=dag_fligoo_etl
AIRFLOW_CTX_TASK_ID=run_etl_task
AIRFLOW_CTX_EXECUTION_DATE=2023-10-06T11:01:06.429640+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-06T11:01:06.429640+00:00
[2023-10-06 11:01:08,384] {logging_mixin.py:109} INFO - >>> Running 'etl' function. Logged at 2023-10-06 11:01:08.384462+00:00
[2023-10-06 11:01:08,385] {logging_mixin.py:109} INFO - >>> Running 'connect_db' function. Logged at 2023-10-06 11:01:08.385058+00:00
[2023-10-06 11:01:08,385] {logging_mixin.py:109} INFO - Connecting to DB
[2023-10-06 11:01:08,398] {logging_mixin.py:109} INFO - >>> Function: 'connect_db' executed. Logged at 2023-10-06 11:01:08.385058+00:00
[2023-10-06 11:01:08,398] {logging_mixin.py:109} INFO - >>> Running 'extract' function. Logged at 2023-10-06 11:01:08.398501+00:00
[2023-10-06 11:01:08,398] {logging_mixin.py:109} INFO - Reading dataset from http://api.aviationstack.com/v1/flights
[2023-10-06 11:01:09,260] {logging_mixin.py:109} INFO - >>> Function: 'extract' executed. Logged at 2023-10-06 11:01:08.398501+00:00
[2023-10-06 11:01:09,261] {logging_mixin.py:109} INFO - >>> Running 'transform' function. Logged at 2023-10-06 11:01:09.261561+00:00
[2023-10-06 11:01:09,262] {logging_mixin.py:109} INFO - Transforming data
[2023-10-06 11:01:09,286] {warnings.py:110} WARNING - /opt/***/dags/dag_fligoo_etl.py:105: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['departure_timezone'] = df['departure_timezone'].str.replace('/', ' - ')

[2023-10-06 11:01:09,288] {warnings.py:110} WARNING - /opt/***/dags/dag_fligoo_etl.py:106: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['arrival_timezone'] = df['arrival_timezone'].str.replace('/', ' - ')

[2023-10-06 11:01:09,289] {logging_mixin.py:109} INFO - >>> Function: 'transform' executed. Logged at 2023-10-06 11:01:09.261561+00:00
[2023-10-06 11:01:09,289] {logging_mixin.py:109} INFO - >>> Running 'load_to_db' function. Logged at 2023-10-06 11:01:09.289800+00:00
[2023-10-06 11:01:09,290] {logging_mixin.py:109} INFO - Loading dataframe to DB on table: testdata
[2023-10-06 11:01:09,380] {logging_mixin.py:109} INFO - >>> Function: 'load_to_db' executed. Logged at 2023-10-06 11:01:09.289800+00:00
[2023-10-06 11:01:09,381] {logging_mixin.py:109} INFO - >>> Function: 'etl' executed. Logged at 2023-10-06 11:01:08.384462+00:00
[2023-10-06 11:01:09,381] {python.py:175} INFO - Done. Returned value was: None
[2023-10-06 11:01:09,404] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag_fligoo_etl, task_id=run_etl_task, execution_date=20231006T110106, start_date=20231006T110108, end_date=20231006T110109
[2023-10-06 11:01:09,445] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-10-06 11:01:09,505] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
