[2023-10-06 11:07:48,927] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_fligoo_etl_v2.run_tables_exists_task manual__2023-10-06T11:07:42.671901+00:00 [queued]>
[2023-10-06 11:07:48,957] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_fligoo_etl_v2.run_tables_exists_task manual__2023-10-06T11:07:42.671901+00:00 [queued]>
[2023-10-06 11:07:48,958] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-10-06 11:07:48,958] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2023-10-06 11:07:48,959] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-10-06 11:07:48,988] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): run_tables_exists_task> on 2023-10-06 11:07:42.671901+00:00
[2023-10-06 11:07:48,995] {standard_task_runner.py:52} INFO - Started process 2843 to run task
[2023-10-06 11:07:49,001] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_fligoo_etl_v2', 'run_tables_exists_task', 'manual__2023-10-06T11:07:42.671901+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_fligoo_etl.py', '--cfg-path', '/tmp/tmprgolk4h0', '--error-file', '/tmp/tmpcjspn53s']
[2023-10-06 11:07:49,003] {standard_task_runner.py:77} INFO - Job 7: Subtask run_tables_exists_task
[2023-10-06 11:07:49,089] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_fligoo_etl_v2.run_tables_exists_task manual__2023-10-06T11:07:42.671901+00:00 [running]> on host f0647ca95f12
[2023-10-06 11:07:49,176] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=dag_fligoo_etl_v2
AIRFLOW_CTX_TASK_ID=run_tables_exists_task
AIRFLOW_CTX_EXECUTION_DATE=2023-10-06T11:07:42.671901+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-06T11:07:42.671901+00:00
[2023-10-06 11:07:49,179] {logging_mixin.py:109} INFO - >>> Running 'tables_exists' function. Logged at 2023-10-06 11:07:49.178782+00:00
[2023-10-06 11:07:49,179] {logging_mixin.py:109} INFO - >>> Running 'connect_db' function. Logged at 2023-10-06 11:07:49.179451+00:00
[2023-10-06 11:07:49,179] {logging_mixin.py:109} INFO - Connecting to DB
[2023-10-06 11:07:49,207] {logging_mixin.py:109} INFO - >>> Function: 'connect_db' executed. Logged at 2023-10-06 11:07:49.179451+00:00
[2023-10-06 11:07:49,207] {logging_mixin.py:109} INFO - Checking if tables exists
[2023-10-06 11:07:49,208] {logging_mixin.py:109} INFO - >>> Running 'check_table_exists' function. Logged at 2023-10-06 11:07:49.208101+00:00
[2023-10-06 11:07:49,212] {logging_mixin.py:109} INFO - 'testdata' exists in the DB!
[2023-10-06 11:07:49,213] {logging_mixin.py:109} INFO - >>> Function: 'check_table_exists' executed. Logged at 2023-10-06 11:07:49.208101+00:00
[2023-10-06 11:07:49,214] {logging_mixin.py:109} INFO - >>> Function: 'tables_exists' executed. Logged at 2023-10-06 11:07:49.178782+00:00
[2023-10-06 11:07:49,215] {python.py:175} INFO - Done. Returned value was: None
[2023-10-06 11:07:49,238] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag_fligoo_etl_v2, task_id=run_tables_exists_task, execution_date=20231006T110742, start_date=20231006T110748, end_date=20231006T110749
[2023-10-06 11:07:49,305] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-10-06 11:07:49,377] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
